//
// Created by fenix on 4/18/20.
//

#ifndef COUNT_NUMBER_OF_ALL_WORDS_DEBUG_CONTROL_H
#define COUNT_NUMBER_OF_ALL_WORDS_DEBUG_CONTROL_H

#define DEBUG_INFO

#endif //COUNT_NUMBER_OF_ALL_WORDS_DEBUG_CONTROL_H
