//
// Created by fenix on 5/27/20.
//

#ifndef MPI_HEAT_TRANSFER_CODE_CONTROLE_H
#define MPI_HEAT_TRANSFER_CODE_CONTROLE_H

#define ERROR_MSG_ON

#define DEBUG

#define EPSILON 10

#endif //MPI_HEAT_TRANSFER_CODE_CONTROLE_H
